spring:
  datasource:
    url:  jdbc:mysql://mysql:3306/product
    driver-class: com.mysql.cj.jdbc.Driver
    username:  root
    password:  password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

products:
    default:
      pageSize: 20
      sort:
        field.name: sellPrice
---
spring:
  profiles: dev
server:
  port:8080
logging:
  level:
    root: INFO
    com.poc: INFO

---
spring:
  profiles: uat
server:
  port: 9090
logging:
  level:
    root: WARN
    com.poc: INFO

---
spring:
  profiles: prod
server:
  port: 9898
logging:
  level:
    root: ERROR
    com.poc: WARN